"use client";
import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import Header from "./header";
import Sidebar from "./sidebar";
import { Provider } from "react-redux";
import { store } from "@/redux/store";
import Modal from "@/components/modal";
import Drawer from "@/lib/drawer";
import ConfirmModal from "@/components/confirm-modal";

const Urbanist = localFont({
  src: [
    { path: "../assets/fonts/Urbanist-Thin.ttf", weight: "100" },
    { path: "../assets/fonts/Urbanist-ExtraLight.ttf", weight: "200" },
    { path: "../assets/fonts/Urbanist-Light.ttf", weight: "300" },
    { path: "../assets/fonts/Urbanist-Regular.ttf", weight: "400" },
    { path: "../assets/fonts/Urbanist-Medium.ttf", weight: "500" },
    { path: "../assets/fonts/Urbanist-SemiBold.ttf", weight: "600" },
    { path: "../assets/fonts/Urbanist-Bold.ttf", weight: "700" },
    { path: "../assets/fonts/Urbanist-ExtraBold.ttf", weight: "800" },
    { path: "../assets/fonts/Urbanist-Black.ttf", weight: "900" },
  ],
});

// export const metadata: Metadata = {
//   title: "Learning App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning className={Urbanist.className}>
        <Provider store={store}>
          <div className="bg-slate-300 h-screen flex flex-col">
            <Header />
            <div className="flex-1 flex h-0 text-sm">
              <Sidebar />
              <div className="bg-white flex-1 overflow-y-auto scrollbar p-5 text-grey-c900">{children}</div>
            </div>
          </div>
          <Modal />
          <Drawer />
          <ConfirmModal />
        </Provider>
      </body>
    </html>
  );
}
