"use client";
import "./globals.css";
import localFont from "next/font/local";
import Header from "./header";
import Sidebar from "./sidebar";
import { Provider } from "react-redux";
import { store } from "@/redux/store";
import Modal from "@/components/modal";
import Drawer from "@/lib/drawer";
import ConfirmModal from "@/components/confirm-modal";
import Loading from "@/lib/loading";

const Urbanist = localFont({
  src: [
    { path: "../assets/fonts/Urbanist-Thin.ttf", weight: "100" },
    { path: "../assets/fonts/Urbanist-ExtraLight.ttf", weight: "200" },
    { path: "../assets/fonts/Urbanist-Light.ttf", weight: "300" },
    { path: "../assets/fonts/Urbanist-Regular.ttf", weight: "400" },
    { path: "../assets/fonts/Urbanist-Medium.ttf", weight: "500" },
    { path: "../assets/fonts/Urbanist-SemiBold.ttf", weight: "600" },
    { path: "../assets/fonts/Urbanist-Bold.ttf", weight: "700" },
    { path: "../assets/fonts/Urbanist-ExtraBold.ttf", weight: "800" },
    { path: "../assets/fonts/Urbanist-Black.ttf", weight: "900" },
  ],
});

const Questrial = localFont({
  src: [
    {
      path: "../assets/fonts/SFUFuturaBook.woff2",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-questrial",
});

// export const metadata: Metadata = {
//   title: "Learning App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={`${Questrial.variable}`}>
      <body suppressHydrationWarning className={`${Urbanist.className}`}>
        <Provider store={store}>
          <div>
            {children}
          </div>
          <Modal />
          <Drawer />
          <ConfirmModal />
          <Loading />
        </Provider>
      </body>
    </html>
  );
}
